image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build
  - mv build public
  - 'echo -e "User-agent: *\nDisallow: /" > public/robots.txt'
  artifacts:
    paths:
    - public
  only:
  - master
