image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    paths:
    - node_modules/
  script:
  - yarn install
  - yarn run build
  artifacts:
    paths:
    - build

pages:
  stage: deploy
  script:
  - mv build public
  - 'echo -e "User-agent: *\nDisallow: /" > public/robots.txt'
  artifacts:
    paths:
    - public
  only:
  - master
